
import { trackError } from './telemetry.js';
import DOMPurify from 'dompurify';

/**
 * Extracts actionable commands from an AI's response text block.
 *
 * @param {string} aiResponseString - The text generated by the AI agent
 * @returns {object} { hasAction: boolean, command: object | null }
 */
export const parseAICommand = (aiResponseString) => {
  try {
    if (typeof aiResponseString !== 'string') {
      return { hasAction: false };
    }

    const match = aiResponseString.match(/\[SYSTEM_ACTION\]\s*(.+)/i);

    if (match && match[1]) {
      let commandPayload = match[1].trim();
      let parsedCommand = null;

      try {
          parsedCommand = JSON.parse(commandPayload);
      } catch(e) {
          // Fallback if not valid JSON, treat as raw text
          parsedCommand = { type: 'raw', payload: DOMPurify.sanitize(commandPayload), timestamp: new Date().toISOString() };
      }

      if (parsedCommand && typeof parsedCommand === 'object') {
          // Deep sanitize nested payload
          const sanitizePayload = (obj) => {
              if (typeof obj === 'string') {
                  // Ensure markdown codeblocks or quotes within strings aren't broken by sanitization, but still strip active scripts
                  return DOMPurify.sanitize(obj, { ALLOWED_TAGS: ['b', 'i', 'em', 'strong', 'a', 'p', 'br', 'ul', 'ol', 'li', 'code', 'pre'] });
              } else if (Array.isArray(obj)) {
                  return obj.map(sanitizePayload);
              } else if (obj !== null && typeof obj === 'object') {
                  const result = {};
                  for (const key in obj) {
                      result[key] = sanitizePayload(obj[key]);
                  }
                  return result;
              }
              return obj;
          };

          const type = typeof parsedCommand.type === 'string' ? DOMPurify.sanitize(parsedCommand.type) : 'unknown';
          const target = typeof parsedCommand.target === 'string' ? DOMPurify.sanitize(parsedCommand.target) : 'system';
          const payload = sanitizePayload(parsedCommand.payload);
          const timestamp = typeof parsedCommand.timestamp === 'string' ? DOMPurify.sanitize(parsedCommand.timestamp) : new Date().toISOString();

          return {
            hasAction: true,
            command: {
                type,
                target,
                payload,
                timestamp
            }
          };
      }
    }

    return { hasAction: false };
  } catch (error) {
    trackError(error, { context: 'parseAICommand' });
    return { hasAction: false };
  }
};
